# Array vs Lists

In [1]:
import numpy as np

In [6]:
a= np.array([1,2])
b= np.array([3,4])

In [9]:
for x, y in zip(a, b):
    print(x, y)


1
2


![equation](https://latex.codecogs.com/svg.image?Cos(\Theta&space;)&space;&space;=&space;\frac{A.B}{\left\|A&space;\right\|\left\|B\right\|})


In [10]:
a @ b

11

In [22]:
amag = np.sqrt((a**2).sum())
amag

2.23606797749979


In [23]:
np.linalg.norm(a)

2.23606797749979

In [19]:
bmag = np.sqrt((b**2).sum())
bmag

5.0

In [20]:
cosab = a  @ b / (amag   * bmag)
cosab

0.9838699100999074

In [25]:
angle  = np.arccos(cosab)
angle

0.17985349979247847

array([1500.,  700.])

# Solving linera equations

![equation](https://latex.codecogs.com/svg.image?AX&space;=&space;B)

![equation](https://latex.codecogs.com/svg.image?X&space;=&space;A^{-1}B)

In [37]:
a = np.array([[1,1],[1.5,4]])
b = np.array([2200, 5050])

In [36]:
np.linalg.solve(a, b)

array([1500.,  700.])

In [38]:
np.linalg.inv(a).dot(b)

array([1500.,  700.])

# Generating Data

In [40]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
10 * np.ones((3,3))


array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [43]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
np.random.random((2,3))

array([[0.22041143, 0.5122255 , 0.8797516 ],
       [0.09561313, 0.09125272, 0.27538091]])

In [47]:
np.random.randn(2,3)

array([[-0.0901469 ,  0.38874422,  1.45806164],
       [ 0.12616383, -0.30540451, -0.01672731]])

In [63]:
R = np.random.randn(1000)

In [64]:
R.mean()

0.03403340440713267

In [65]:
np.mean(R)

0.03403340440713267

In [66]:
R.var()

1.09048720180173

In [67]:
R.std()

1.0442639521700106

In [70]:
np.allclose(R.var(), R.std()**2)

True

In [73]:
R =  np.random.randn(10000, 3)

In [74]:
R.mean(axis=0)

array([ 0.00510683, -0.00938775, -0.00402588])

In [75]:
R.mean(axis=1).shape

(10000,)

In [76]:
np.cov(R.T)

array([[ 0.97457232, -0.00654516,  0.00250195],
       [-0.00654516,  0.98198081,  0.01871512],
       [ 0.00250195,  0.01871512,  1.00296985]])

In [77]:
np.random.randint(1, 10, (2,2))

array([[5, 3],
       [7, 5]])

In [78]:
np.random.choice(10,(2,2))

array([[4, 6],
       [7, 1]])